### ISSUE TITLE
Doesn't omit last object

### ISSUE THREAD

**Issue by jgoux** [jonschlinkert/omit-empty#3]
Hello,

when I pass this structure to omitEmpty : 

``` js
const test = {
  baz: [
    { foo: "foo" },
    { bar: '' }
  ]
}
```

it doesn't suppress the last object `{ bar: '' }`

**Comment by doowb** [comment]
This doesn't recurse into arrays. [This test](https://github.com/jonschlinkert/omit-empty/blob/master/test.js#L69-L72) is an example of an array with an empty nested array that doesn't get removed.

I'm not sure if this is a feature or a bug, but if a change is to be made, it'll probably go [here](https://github.com/jonschlinkert/omit-empty/blob/master/index.js#L46)

**Comment by jonschlinkert** [comment]
thoughts? should we recurse into arrays?

**Comment by kakadiadarpan** [comment]
Hi @jonschlinkert,
I have fixed this issue. Please review it and merge it if you think it's good enough.

[https://github.com/jonschlinkert/omit-empty/pull/4](url)
