### ISSUE TITLE
Unable to install "omit-empty:0.4.0" using Bower

### ISSUE THREAD

**Issue by pavanesh2009** [jonschlinkert/omit-empty#5]
Hi, 

I am trying to install "omit-empty": "0.4.0" in angular based project.

Error:
bower omit-empty#0.4.0       ENOTFOUND Package omit-empty not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Could you please provide a hint here, Also Should we consider index.js file to be added in angular project to utilize omit-empty module.

Thanks!

**Comment by jonschlinkert** [comment]
Apologies for the very late reply. Closing since bower support has been removed.
